version: '3.7'
services:
  postgres:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - ./api/db/postgres-test-data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - "80:80" 
      - "443:443"
    volumes:
      - ./ngnix/app:/usr/share/nginx/html
      - ./ngnix/nginx.conf:/etc/nginx/nginx.conf
      - ./ngnix/site/conf:/etc/nginx/conf.d
    restart: unless-stopped
